<a href="https://colab.research.google.com/github/gianellannie/telecom-x/blob/main/TelecomX_LATAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#📌 Extracción

In [76]:
import json

In [89]:
datos_diccionario = json.load(open('/content/TelecomX_Data.json'))

In [1]:
import pandas as pd

In [90]:
datos_normalizados = pd.json_normalize(datos_diccionario)
datos_normalizados.head()

customerID Churn customer.gender  customer.SeniorCitizen customer.Partner  \
0  0002-ORFBO    No          Female                       0              Yes   
1  0003-MKNFE    No            Male                       0               No   
2  0004-TLHLJ   Yes            Male                       0               No   
3  0011-IGKFF   Yes            Male                       1              Yes   
4  0013-EXCHZ   Yes          Female                       1              Yes   

  customer.Dependents  customer.tenure phone.PhoneService phone.MultipleLines  \
0                 Yes                9                Yes                  No   
1                  No                9                Yes                 Yes   
2                  No                4                Yes                  No   
3                  No               13                Yes                  No   
4                  No                3                Yes                  No   

  internet.InternetService  ... internet.OnlineBackup  \
0                      DSL  ...                   Yes   
1                      DSL  ...                    No   
2              Fiber optic  ...                    No   
3              Fiber optic  ...                   Yes   
4              Fiber optic  ...                    No   

  internet.DeviceProtection internet.TechSupport internet.StreamingTV  \
0                        No                  Yes                  Yes   
1                        No                   No                   No   
2                       Yes                   No                   No   
3                       Yes                   No                  Yes   
4                        No                  Yes                  Yes   

  internet.StreamingMovies account.Contract account.PaperlessBilling  \
0                       No         One year                      Yes   
1                      Yes   Month-to-month                       No   
2                       No   Month-to-month                      Yes   
3                      Yes   Month-to-month                      Yes   
4                       No   Month-to-month                      Yes   

  account.PaymentMethod account.Charges.Monthly  account.Charges.Total  
0          Mailed check                    65.6                  593.3  
1          Mailed check                    59.9                  542.4  
2      Electronic check                    73.9                 280.85  
3      Electronic check                    98.0                1237.85  
4          Mailed check                    83.9                  267.4  

[5 rows x 21 columns]

#🔧 Transformación

In [243]:
columnas_relevantes = ['Churn','customer.gender','customer.SeniorCitizen','customer.Partner','customer.Dependents','customer.tenure','account.Contract','account.PaperlessBilling','account.PaymentMethod','account.Charges.Monthly','account.Charges.Total']
datos = datos_normalizados[columnas_relevantes]
datos.head()

Churn customer.gender  customer.SeniorCitizen customer.Partner  \
0    No          Female                       0              Yes   
1    No            Male                       0               No   
2   Yes            Male                       0               No   
3   Yes            Male                       1              Yes   
4   Yes          Female                       1              Yes   

  customer.Dependents  customer.tenure account.Contract  \
0                 Yes                9         One year   
1                  No                9   Month-to-month   
2                  No                4   Month-to-month   
3                  No               13   Month-to-month   
4                  No                3   Month-to-month   

  account.PaperlessBilling account.PaymentMethod  account.Charges.Monthly  \
0                      Yes          Mailed check                     65.6   
1                       No          Mailed check                     59.9   
2                      Yes      Electronic check                     73.9   
3                      Yes      Electronic check                     98.0   
4                      Yes          Mailed check                     83.9   

  account.Charges.Total  
0                 593.3  
1                 542.4  
2                280.85  
3               1237.85  
4                 267.4

In [205]:
pd.unique(datos['Churn'])

array(['No', 'Yes', ''], dtype=object)

In [206]:
pd.unique(datos['customer.gender'])

array(['Female', 'Male'], dtype=object)

In [177]:
pd.unique(datos['customer.SeniorCitizen'])

array([0, 1])

In [178]:
pd.unique(datos['customer.Partner'])

array(['Yes', 'No'], dtype=object)

In [179]:
pd.unique(datos['customer.Dependents'])

array(['Yes', 'No'], dtype=object)

In [180]:
pd.unique(datos['customer.tenure'])

array([ 9,  4, 13,  3, 71, 63,  7, 65, 54, 72,  5, 56, 34,  1, 45, 50, 23,
       55, 26, 69, 11, 37, 49, 66, 67, 20, 43, 59, 12, 27,  2, 25, 29, 14,
       35, 64, 39, 40,  6, 30, 70, 57, 58, 16, 32, 33, 10, 21, 61, 15, 44,
       22, 24, 19, 47, 62, 46, 52,  8, 60, 48, 28, 41, 53, 68, 51, 31, 36,
       17, 18, 38, 42,  0])

In [181]:
pd.unique(datos['account.Contract'])

array(['One year', 'Month-to-month', 'Two year'], dtype=object)

In [182]:
pd.unique(datos['account.PaperlessBilling'])

array(['Yes', 'No'], dtype=object)

In [183]:
pd.unique(datos['account.PaymentMethod'])

array(['Mailed check', 'Electronic check', 'Credit card (automatic)',
       'Bank transfer (automatic)'], dtype=object)

In [184]:
pd.unique(datos['account.Charges.Monthly'])

array([65.6 , 59.9 , 73.9 , ..., 91.75, 68.8 , 67.85])

In [185]:
pd.unique(datos['account.Charges.Total'])

array(['593.3', '542.4', '280.85', ..., '742.9', '4627.65', '3707.6'],
      dtype=object)

In [244]:
datos = datos.query('Churn != ""')
datos.head()

Churn customer.gender  customer.SeniorCitizen customer.Partner  \
0    No          Female                       0              Yes   
1    No            Male                       0               No   
2   Yes            Male                       0               No   
3   Yes            Male                       1              Yes   
4   Yes          Female                       1              Yes   

  customer.Dependents  customer.tenure account.Contract  \
0                 Yes                9         One year   
1                  No                9   Month-to-month   
2                  No                4   Month-to-month   
3                  No               13   Month-to-month   
4                  No                3   Month-to-month   

  account.PaperlessBilling account.PaymentMethod  account.Charges.Monthly  \
0                      Yes          Mailed check                     65.6   
1                       No          Mailed check                     59.9   
2                      Yes      Electronic check                     73.9   
3                      Yes      Electronic check                     98.0   
4                      Yes          Mailed check                     83.9   

  account.Charges.Total  
0                 593.3  
1                 542.4  
2                280.85  
3               1237.85  
4                 267.4

In [152]:
import numpy as np

In [246]:
datos['account.Charges.Total'] = datos['account.Charges.Total'].replace(' ', '0.0').astype(np.float64)

In [245]:
columnas_numericas = ['Churn','customer.Partner','customer.Dependents','account.PaperlessBilling']
datos[columnas_numericas] = datos[columnas_numericas].map(lambda x: 1 if x == 'Yes' else 0).astype(np.int64)
datos.head()

Churn customer.gender  customer.SeniorCitizen  customer.Partner  \
0      0          Female                       0                 1   
1      0            Male                       0                 0   
2      1            Male                       0                 0   
3      1            Male                       1                 1   
4      1          Female                       1                 1   

   customer.Dependents  customer.tenure account.Contract  \
0                    1                9         One year   
1                    0                9   Month-to-month   
2                    0                4   Month-to-month   
3                    0               13   Month-to-month   
4                    0                3   Month-to-month   

   account.PaperlessBilling account.PaymentMethod  account.Charges.Monthly  \
0                         1          Mailed check                     65.6   
1                         0          Mailed check                     59.9   
2                         1      Electronic check                     73.9   
3                         1      Electronic check                     98.0   
4                         1          Mailed check                     83.9   

  account.Charges.Total  
0                 593.3  
1                 542.4  
2                280.85  
3               1237.85  
4                 267.4

In [247]:
datos.dtypes

Churn                         int64
customer.gender              object
customer.SeniorCitizen        int64
customer.Partner              int64
customer.Dependents           int64
customer.tenure               int64
account.Contract             object
account.PaperlessBilling      int64
account.PaymentMethod        object
account.Charges.Monthly     float64
account.Charges.Total       float64
dtype: object

In [251]:
datos['Cuentas_Diarias'] = datos['account.Charges.Monthly'] / 30
datos.head()

Churn customer.gender  customer.SeniorCitizen  customer.Partner  \
0      0          Female                       0                 1   
1      0            Male                       0                 0   
2      1            Male                       0                 0   
3      1            Male                       1                 1   
4      1          Female                       1                 1   

   customer.Dependents  customer.tenure account.Contract  \
0                    1                9         One year   
1                    0                9   Month-to-month   
2                    0                4   Month-to-month   
3                    0               13   Month-to-month   
4                    0                3   Month-to-month   

   account.PaperlessBilling account.PaymentMethod  account.Charges.Monthly  \
0                         1          Mailed check                     65.6   
1                         0          Mailed check                     59.9   
2                         1      Electronic check                     73.9   
3                         1      Electronic check                     98.0   
4                         1          Mailed check                     83.9   

   account.Charges.Total  Cuentas_Diarias  
0                 593.30         2.186667  
1                 542.40         1.996667  
2                 280.85         2.463333  
3                1237.85         3.266667  
4                 267.40         2.796667

In [252]:
datos = datos.rename(columns={'Churn':'Evasion_Cliente','customer.gender':'Genero','customer.SeniorCitizen':'Es_Adulto_Mayor','customer.Partner':'Tiene_Pareja',
                              'customer.Dependents':'Tiene_Dependientes','customer.tenure':'Meses_Contrato','account.Contract':'Tipo_Contrato',
                              'account.PaperlessBilling':'Factura_Electronica','account.PaymentMethod':'Metodo_Pago','account.Charges.Monthly':'Facturacion_Mensual',
                              'account.Charges.Total':'Facturacion_Total'})
datos.head()

Evasion_Cliente  Genero  Es_Adulto_Mayor  Tiene_Pareja  Tiene_Dependientes  \
0                0  Female                0             1                   1   
1                0    Male                0             0                   0   
2                1    Male                0             0                   0   
3                1    Male                1             1                   0   
4                1  Female                1             1                   0   

   Meses_Contrato   Tipo_Contrato  Factura_Electronica       Metodo_Pago  \
0               9        One year                    1      Mailed check   
1               9  Month-to-month                    0      Mailed check   
2               4  Month-to-month                    1  Electronic check   
3              13  Month-to-month                    1  Electronic check   
4               3  Month-to-month                    1      Mailed check   

   Facturacion_Mensual  Facturacion_Total  Cuentas_Diarias  
0                 65.6             593.30         2.186667  
1                 59.9             542.40         1.996667  
2                 73.9             280.85         2.463333  
3                 98.0            1237.85         3.266667  
4                 83.9             267.40         2.796667

#📊 Carga y análisis

#📄Informe final